vcs-facade:
  vcs:
    services:
      - id: test-bitbucket
        type: BITBUCKET
        http-url: http://${VCS_FACADE_VCS_HOST}
        ssh-url: ssh://git@${VCS_FACADE_VCS_HOST}
        username: admin
        password: admin
  opensearch:
    enabled: false